name: Greetings

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/checkout@v2
    - name: Saludo
      run: echo 'saludo'
